Repository andreknieriem/photobooth, pull requests merged in 2020-01, with the labels that each got.

#196 Apply filter on picture taken
  README.md
  index.php
  lib/db.php
  resources/js/core.js
Labels: WIP

#200 Display collage count before taking photo
  admin/index.php
  api/takePic.php
  lib/config.php
  lib/configsetup.inc.php
  resources/js/core.js
Labels: enhancement

#194 Design: optional rounded corners config
  .gitignore
  admin/index.php
  chromakeying.php
  config/config.inc.php
  gallery.php
  index.php
  lib/configsetup.inc.php
  resources/lang/de.js
  resources/lang/en.js
  resources/lang/es.js
  resources/lang/fr.js
  resources/lang/gr.js
  resources/sass/rounded.scss
  resources/sass/style.scss
Labels: design, feature

#118 admin: add simple login
  .gitignore
  admin/index.php
  api/admin.php
  config/config.inc.php
  index.php
  lib/configsetup.inc.php
  login.php
  logout.php
  resources/js/login.js
  resources/lang/de.js
  resources/lang/en.js
  resources/lang/es.js
  resources/lang/fr.js
  resources/lang/gr.js
  resources/sass/login.scss
  resources/sass/partials/_button.scss
  resources/sass/rounded.scss
  scripts/pack-build.js
Labels: feature, review

#211 Allow using device cam to take Pictures
  api/takePic.php
  config/config.inc.php
  index.php
  lib/configsetup.inc.php
  resources/js/core.js
  resources/lang/de.js
  resources/lang/en.js
  resources/lang/es.js
  resources/lang/fr.js
  resources/lang/gr.js
  resources/sass/style.scss
Labels: feature

#218 Css Styling in Admin Panel
  .gitignore
  README.md
  admin/index.php
  chromakeying.php
  config/config.inc.php
  lib/config.php
  lib/configsetup.inc.php
  resources/js/theme.js
  resources/lang/de.js
  resources/lang/en.js
  resources/lang/es.js
  resources/lang/fr.js
  resources/lang/gr.js
  resources/sass/admin.scss
  resources/sass/chromakeying.scss
  resources/sass/login.scss
  resources/sass/modules/_theme.scss
  resources/sass/partials/_basic.scss
  resources/sass/partials/_button.scss
  resources/sass/partials/_gallery.scss
  resources/sass/partials/_ribbon.scss
  resources/sass/partials/_sidenav.scss
  resources/sass/rounded.scss
  resources/sass/style.scss
  resources/sass/vendor/_photoswipe.scss
Labels: design, feature
